<?php

use Illuminate\Database\Seeder;

class AdminsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('admins')->delete();
        
        \DB::table('admins')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Paolo Braun',
                'avatar' => NULL,
                'username' => NULL,
                'about' => NULL,
                'phone' => NULL,
                'phone_hidden' => NULL,
                'email' => 'lang.eileen@example.net',
                'password' => '$2y$10$usq65fpmAGxap/VnIxVfR.q2ziaB.mAklW1rfVPh8Y9PGeHynVbGC',
                'ip_addr' => NULL,
                'last_login_at' => NULL,
                'api_token' => 'TYIz0Dl4EzmKVDac1MEyUCrV16nmMZAkMHk6byttwuF1rH9jWpkvUU5jCoS3',
                'email_token' => NULL,
                'verified_email' => 0,
                'active' => 1,
                'blocked' => 0,
                'closed' => 0,
                'remember_token' => 'xThP91LOXJ',
                'created_at' => '2018-03-04 10:09:56',
                'updated_at' => '2018-03-04 10:09:56',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Violette Tremblay',
                'avatar' => NULL,
                'username' => NULL,
                'about' => NULL,
                'phone' => NULL,
                'phone_hidden' => NULL,
                'email' => 'gleason.jeromy@example.net',
                'password' => '$2y$10$usq65fpmAGxap/VnIxVfR.q2ziaB.mAklW1rfVPh8Y9PGeHynVbGC',
                'ip_addr' => NULL,
                'last_login_at' => NULL,
                'api_token' => 'c4lwHnYtppy5KFfxlrjDzIu9INUZwANiqfhr1JaVyRFO1PzY7bbogXKYfq5p',
                'email_token' => NULL,
                'verified_email' => 0,
                'active' => 1,
                'blocked' => 0,
                'closed' => 0,
                'remember_token' => 'W4atF6mQD3',
                'created_at' => '2018-03-04 10:09:56',
                'updated_at' => '2018-03-04 10:09:56',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Dr. Ashleigh Hackett',
                'avatar' => NULL,
                'username' => NULL,
                'about' => NULL,
                'phone' => NULL,
                'phone_hidden' => NULL,
                'email' => 'jamey37@example.net',
                'password' => '$2y$10$usq65fpmAGxap/VnIxVfR.q2ziaB.mAklW1rfVPh8Y9PGeHynVbGC',
                'ip_addr' => NULL,
                'last_login_at' => NULL,
                'api_token' => 'OZ9qMEMMBShspsFA4uZFbq5Lrme2iNMNxST2NfohGa887ttb5nxPSBSvdFee',
                'email_token' => NULL,
                'verified_email' => 0,
                'active' => 1,
                'blocked' => 0,
                'closed' => 0,
                'remember_token' => 'UWZG09jyxp',
                'created_at' => '2018-03-04 10:09:56',
                'updated_at' => '2018-03-04 10:09:56',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Vicente Casper',
                'avatar' => NULL,
                'username' => NULL,
                'about' => NULL,
                'phone' => NULL,
                'phone_hidden' => NULL,
                'email' => 'schuppe.flavio@example.net',
                'password' => '$2y$10$usq65fpmAGxap/VnIxVfR.q2ziaB.mAklW1rfVPh8Y9PGeHynVbGC',
                'ip_addr' => NULL,
                'last_login_at' => NULL,
                'api_token' => 'k6yKw9l0FVOhMc2hR9EDetIBiM10sKKDwyGPxsM2prPQexBcBrQTia8L9ZEC',
                'email_token' => NULL,
                'verified_email' => 0,
                'active' => 1,
                'blocked' => 0,
                'closed' => 0,
                'remember_token' => 'DPYKcz4kcz',
                'created_at' => '2018-03-04 10:09:56',
                'updated_at' => '2018-03-04 10:09:56',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Amanda Spinka',
                'avatar' => NULL,
                'username' => NULL,
                'about' => NULL,
                'phone' => NULL,
                'phone_hidden' => NULL,
                'email' => 'horacio.rau@example.org',
                'password' => '$2y$10$usq65fpmAGxap/VnIxVfR.q2ziaB.mAklW1rfVPh8Y9PGeHynVbGC',
                'ip_addr' => NULL,
                'last_login_at' => NULL,
                'api_token' => 'NjjvOeztJX688RQ3WeTGcvBXCohOIQe3cnNjqG5kasZHtkDn1leRJDDBHeiY',
                'email_token' => NULL,
                'verified_email' => 0,
                'active' => 1,
                'blocked' => 0,
                'closed' => 0,
                'remember_token' => 'YKCTzUknUL',
                'created_at' => '2018-03-04 10:09:56',
                'updated_at' => '2018-03-04 10:09:56',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Devon Purdy',
                'avatar' => NULL,
                'username' => NULL,
                'about' => NULL,
                'phone' => NULL,
                'phone_hidden' => NULL,
                'email' => 'willow76@example.com',
                'password' => '$2y$10$usq65fpmAGxap/VnIxVfR.q2ziaB.mAklW1rfVPh8Y9PGeHynVbGC',
                'ip_addr' => NULL,
                'last_login_at' => NULL,
                'api_token' => '0VijHUSh86HqupUZkqjWHVa1cwHJqEkxMLq7eZsYJ0TOMEC50qpToIlUDgCp',
                'email_token' => NULL,
                'verified_email' => 0,
                'active' => 1,
                'blocked' => 0,
                'closed' => 0,
                'remember_token' => 'OZfOpoLVMO',
                'created_at' => '2018-03-04 10:09:56',
                'updated_at' => '2018-03-04 10:09:56',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Ms. Eula Greenfelder DDS',
                'avatar' => NULL,
                'username' => NULL,
                'about' => NULL,
                'phone' => NULL,
                'phone_hidden' => NULL,
                'email' => 'jedidiah.satterfield@example.net',
                'password' => '$2y$10$usq65fpmAGxap/VnIxVfR.q2ziaB.mAklW1rfVPh8Y9PGeHynVbGC',
                'ip_addr' => NULL,
                'last_login_at' => NULL,
                'api_token' => 'FO102oKHg56MHSGv9w4mGjoEVuPXYha51DEggRP3ZIhOtlI9tuJkayLTMTZm',
                'email_token' => NULL,
                'verified_email' => 0,
                'active' => 1,
                'blocked' => 0,
                'closed' => 0,
                'remember_token' => 'iBOdqnerD1',
                'created_at' => '2018-03-04 10:09:56',
                'updated_at' => '2018-03-04 10:09:56',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Rosalyn Effertz',
                'avatar' => NULL,
                'username' => NULL,
                'about' => NULL,
                'phone' => NULL,
                'phone_hidden' => NULL,
                'email' => 'lolita.bogan@example.net',
                'password' => '$2y$10$usq65fpmAGxap/VnIxVfR.q2ziaB.mAklW1rfVPh8Y9PGeHynVbGC',
                'ip_addr' => NULL,
                'last_login_at' => NULL,
                'api_token' => 'mPgWWJKicbdn0FIG2bn4Ji0PpaGs7BdfU5Nbm9OzSxANv9X5388tNNrkqb1n',
                'email_token' => NULL,
                'verified_email' => 0,
                'active' => 1,
                'blocked' => 0,
                'closed' => 0,
                'remember_token' => 'OctcMj4o0P',
                'created_at' => '2018-03-04 10:09:56',
                'updated_at' => '2018-03-04 10:09:56',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Bridget Sawayn',
                'avatar' => NULL,
                'username' => NULL,
                'about' => NULL,
                'phone' => NULL,
                'phone_hidden' => NULL,
                'email' => 'candelario.rohan@example.com',
                'password' => '$2y$10$usq65fpmAGxap/VnIxVfR.q2ziaB.mAklW1rfVPh8Y9PGeHynVbGC',
                'ip_addr' => NULL,
                'last_login_at' => NULL,
                'api_token' => 'rxFhdTXdXlNoHMAsgeDFVfOCIyAaEoKWPOm0N4R9db9HevzHkLwrefNK55BQ',
                'email_token' => NULL,
                'verified_email' => 0,
                'active' => 1,
                'blocked' => 0,
                'closed' => 0,
                'remember_token' => 's7KYLb2QSq',
                'created_at' => '2018-03-04 10:09:56',
                'updated_at' => '2018-03-04 10:09:56',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Gust Gorczany',
                'avatar' => NULL,
                'username' => NULL,
                'about' => NULL,
                'phone' => NULL,
                'phone_hidden' => NULL,
                'email' => 'toy.savannah@example.org',
                'password' => '$2y$10$usq65fpmAGxap/VnIxVfR.q2ziaB.mAklW1rfVPh8Y9PGeHynVbGC',
                'ip_addr' => NULL,
                'last_login_at' => NULL,
                'api_token' => 'fNvtO7f3eNBYs6ehODzVcYah1WjxV4zFI9Aho8ViEtE6F0z2uKCC4xRHXAcJ',
                'email_token' => NULL,
                'verified_email' => 0,
                'active' => 1,
                'blocked' => 0,
                'closed' => 0,
                'remember_token' => 'ZkbzgYkN9Q',
                'created_at' => '2018-03-04 10:09:56',
                'updated_at' => '2018-03-04 10:09:56',
            ),
        ));
        
        
    }
}