language: php

php:
  - 7.1
  - nightly

matrix:
    allow_failures:
        - php: nightly

install:
  - travis_retry composer install --no-interaction --prefer-source
  - mv .env.travis .env
  - php artisan key:generate
